### PR TITLE
Added state experiment for FF

### PR DESCRIPTION
**Pull request by cbrewster**
So this has some pretty interesting results. When doing navigations based on navigating to a new URL, traversal ends up being different compared to doing navigations via `pushState`. I have also noticed a similar thing in Safari as the two yield different results (also different from these results too). I believe that traversing over nav entries from `pushState` should behave the same as traversing over entries from navigating to a new URL.

@asajeffrey

### CODE REVIEW

**Comment by cbrewster** [comment]
Also, do we want to split the actual experiments out to different documents? Compile time is getting pretty long for me and the document is growing. Maybe have the actual experiments separated in different folders and then have a quick overview of the results in the main document?

**Comment by cbrewster** [comment]
FF's behavior with `pushState` is actually really weird. If you run the state based test `history_iframe.html` and advance the first iframe a few times and then use the back arrow, it will take you back to the newtab page instead of traversing that iframe back. That does not seem right at all.

**Comment by asajeffrey** [comment]
At some point I was planning on restructuring the document, and putting the experiments into an appendix, with some summary text in the main body. Does this seem sensible to you?

**Comment by cbrewster** [comment]
@asajeffrey sounds good to me.

**Pull request merged**
