### PR TITLE
Add first experiment

### PR DESCRIPTION
**Pull request by cbrewster**
This experiment tests `Goal 1` in Firefox. I wanted to make sure everything looks good here before doing anymore. As you know I am pretty new to LaTeX, so any suggestions on formatting are welcome.

@asajeffrey (because Github doesn't mark you as participating)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Cool, I'll take a look when I'm back in the US.

**Comment by asajeffrey** [comment]
OK, this looks really nice! I particularly liked the side-by-side screenshots and diagrams.

The only bit of tidying up I'd like to do is to get the diagrams to be all the same size.

**Comment by cbrewster** [comment]
@asajeffrey agreed. It likes to scale it as large as it can be to fit the space. Is there a way to make it not do that?

**Comment by asajeffrey** [comment]
I'll play with it and see what the magic is!

**Comment by asajeffrey** [comment]
Well, I got something to work. Not the prettiest LaTeX I've ever written, but the output looks good.

**Pull request merged**
