### PR TITLE
Counterexample 4

### PR DESCRIPTION
**Pull request by cbrewster**
Don't merge yet, I need to add a part explaining the patch here. I also would like you to look over this example as this shows how navigation is expected to work, but it does not follow the spec: removing all active entries except the current entry of the joint session history and then getting the specified entry at the index of the current entry + delta.

If you would like, I can make this counterexample follow what the spec says to show why it won't work (actually I should do this, but I am tired right now and need sleep).

I am not sure of a patch that would fix this yet.

### CODE REVIEW

**Comment by asajeffrey** [comment]
I think you're going to need a navigation in the example, with a bit of luck going back and forth won't need us to remove documents.

**Comment by cbrewster** [comment]
@asajeffrey I will update the example, its more about the traversal algorithm. If we follow the spec, we can navigate back twice and then navigate forward twice and when going forward it activates the wrong entries.

**Comment by cbrewster** [comment]
So this counterexample should now follow the what the spec says about picking which entry to traverse to and in the counterexample it would yield a weird result as step 4 does not undo step 3. The forward order and backward order do not match up. I can do another test in FF to see how it handles this case.

Edit: Firefox does the correct order and does not follow what the counterexample shows.

**Comment by asajeffrey** [comment]
Hmm. I think the problem here is similar to the one in counterexample 3. The same fix (being more aggressive about deleting documents on navigation) may help here.

**Pull request merged**
